---

- name: >-
      {% if 'context' in k8s_item -%}
        [{{ k8s_item.context }}]{{' '}}
      {%- elif k8s_context -%}
        [{{ k8s_context }}]{{' '}}
      {%- endif %}ensure template is removed: {{ k8s_item.template }}
  k8s:
    state: absent
    definition: "{{ lookup('template', k8s_item.template) | from_yaml }}"
    # Optional auth variables
    context: "{{ k8s_item.context | default(k8s_context | default(omit)) }}"
    api_key: "{{ k8s_item.api_key | default(omit) }}"
    ssl_ca_cert: "{{ k8s_item.ssl_ca_cert | default(omit) }}"
    cert_file: "{{ k8s_item.cert_file | default(omit) }}"
    key_file: "{{ k8s_item.key_file | default(omit) }}"
    host: "{{ k8s_item.host | default(omit) }}"
    username: "{{ k8s_item.username | default(omit) }}"
    password: "{{ k8s_item.password | default(omit) }}"
  # Alway run when k8s_tag is not defined
  # or only run templates that match k8s_tag values
  when: |
    (
      k8s_tag is defined and k8s_tag and
      k8s_item.tag is defined and k8s_item.tag and
      k8s_tag == k8s_item.tag
    ) or (
      k8s_tag is defined and k8s_tag and
      k8s_item.tags is defined and k8s_item.tags and
      k8s_tag in k8s_item.tags
    ) or (
      k8s_tag is not defined
    )
